### ISSUE TITLE
App not being looked up under "Group" on Launchpad Service

### ISSUE THREAD

**Issue by kevindass** [SAP-samples/ui5-deployments#4]
Hi Robin,

Quick question, have you tried configuring app post CF deploy on to the Launchpad Service?

When I do, I could see the app under "Content manager" of Launchpad Service, however when I try to add app into a Group it doesn't show up in results.

Regards,
Kevin Dass

**Comment by kevindass** [comment]
Robin,

I have sent you pull request for this fix

**Comment by ThisIsRobin** [comment]
Indeed, we had not included crossnavigation property in manifest to enable usage in launchpad - good find!

Unfortunately you didn't sign the CLA, so I had to close your pull request, but I just incorporated the required changes.

Thanks again!
Robin
